### CREATE a new patient reposiotry
POST http://lb-4ec0afe3.elb.localhost.localstack.cloud:4000/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "testing with localstack",
  "email": "localstackin@gmail.com",
  "address": "hello street 143",
  "dateOfBirth": "2000-09-29",
  "registeredDate": "2025-04-28"
}

### It will create a new patients