### CREATE a new patient reposiotry
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "AnuragJiKafkaa",
  "email": "text@anurakkafkaa.com",
  "address": "hello street 143",
  "dateOfBirth": "2000-09-29",
  "registeredDate": "2025-04-28"
}

